spring:
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: create-drop
        properties:
          javax:
            persistence:
                  sql-load-script-source: META-INF/sql/data.sql

    datasource:
        url: jdbc:mysql://sql7.freemysqlhosting.net:3306/sql7243207
        username: sql7243207
        password: SNaLDCr1BB
        driver-class-name: com.mysql.jdbc.Driver

