spring:
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: create-drop
        properties:
          javax:
            persistence:
                  sql-load-script-source: META-INF/sql/data.sql

    datasource:
        url: jdbc:mysql://sql2.freemysqlhosting.net:3306/sql2241781
        username: sql2241781
        password: vK5*bP4%
        driver-class-name: com.mysql.jdbc.Driver

